name: Build and submit

on:
  push:
    branches: ['main']

jobs:
  build_android:
    name: Build Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
      - run: eas build --platform android --profile production --non-interactive --json > android-build.json
      - id: upload_android
        run: echo "BUILD_ID=$(jq -r '.builds.android.artifactId' android-build.json)" >> $GITHUB_OUTPUT

  build_ios:
    name: Build iOS app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
      - run: eas build --platform ios --profile production --non-interactive --json > ios-build.json
      - id: upload_ios
        run: echo "BUILD_ID=$(jq -r '.builds.ios.artifactId' ios-build.json)" >> $GITHUB_OUTPUT

  submit_android:
    name: Submit Android
    needs: [build_android]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
      - run: eas submit --platform android --non-interactive --latest
        env:
          EAS_BUILD_ID: ${{ needs.build_android.outputs.BUILD_ID }}

  submit_ios:
    name: Submit iOS
    needs: [build_ios]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
      - run: eas submit --platform ios --non-interactive --latest
        env:
          EAS_BUILD_ID: ${{ needs.build_ios.outputs.BUILD_ID }}
